// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Bai4.Models;

public partial class LichKham
{
    public int MaLich { get; set; }

    public string TenBenhNhan { get; set; }

    public string Sdt { get; set; }

    public DateOnly? NgayKham { get; set; }

    public TimeOnly? GioKham { get; set; }

    public int? MaBs { get; set; }

    public string TrangThai { get; set; }

    public virtual BacSi MaBsNavigation { get; set; }
}