// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Bai3.Models;

public partial class LoaiPhong
{
    public int MaLoai { get; set; }

    public string TenLoai { get; set; }

    public decimal? GiaMoiDem { get; set; }

    public string MoTa { get; set; }

    public virtual ICollection<Phong> Phongs { get; set; } = new List<Phong>();
}