// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Bai3.Models;

public partial class Phong
{
    public int MaPhong { get; set; }

    public string SoPhong { get; set; }

    public int? TangSo { get; set; }

    public string TinhTrang { get; set; }

    public string HinhAnh { get; set; }

    public int? MaLoai { get; set; }

    public virtual LoaiPhong MaLoaiNavigation { get; set; }
}