// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Bai1.Models;

public partial class TheLoaiSach
{
    public int MaTl { get; set; }

    public string TenTheLoai { get; set; }

    public string MoTa { get; set; }

    public int? SoLuongSach { get; set; }

    public DateTime? NgayTao { get; set; }
}